version: '3.8'
services:
  web:
    build: .
    command: ["gunicorn", "booksstore.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2"]
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=dev-secret
      - ALLOWED_HOSTS=127.0.0.1,localhost
    depends_on: []
